from typing import Protocol


class HostBridge(Protocol):
    def log(self, stream: str, text: str) -> None: ...

    def emit_plot(self, figure_index: int, title: str, mime: str, data: str) -> None: ...

    def write_seq(self, filename: str, content: str, mime: str = "text/plain") -> None: ...

    def preferred_plot_format(self) -> str | None: ...
